from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(Site)
admin.site.register(Division)
admin.site.register(Department_E)
admin.site.register(Department_V)
admin.site.register(Area)
admin.site.register(Provinces)
admin.site.register(Gp)
admin.site.register(Department_area)
admin.site.register(Function)
admin.site.register(Job_title)
admin.site.register(Position_E)
admin.site.register(Position_V)
admin.site.register(Contract_type)
admin.site.register(Sexual)
admin.site.register(Ethic_group)
admin.site.register(Marital_status)
admin.site.register(Certificate_E)
admin.site.register(Certificate_V)
admin.site.register(Hi_registered_place)
admin.site.register(Relation_1)
admin.site.register(Relation_2)
admin.site.register(Bo_sung_ho_so)
admin.site.register(Da_nop_thong_tin_nhan_vien)
admin.site.register(Employee)

