from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(Site)
admin.site.register(Division)
admin.site.register(Department_E)
admin.site.register(Department_V)
admin.site.register(Area)
admin.site.register(Provinces)
admin.site.register(Gp)
admin.site.register(Function)
admin.site.register(Position_E)
admin.site.register(Position_V)
admin.site.register(Abbreviation_Position)
admin.site.register(Contract_type)
admin.site.register(Sexual)
admin.site.register(Ethic_group)
admin.site.register(Marital_status)
admin.site.register(Certificate_E)
admin.site.register(Certificate_V)
admin.site.register(University)
admin.site.register(Hi_medical_place)
admin.site.register(Relation_1)
admin.site.register(Relation_2)
admin.site.register(Staff_info_submission)
admin.site.register(Employee)
admin.site.register(Employee_children)
admin.site.register(Probationary_period)

