# Generated by Django 4.0.5 on 2022-10-10 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_department_e_department_e_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children', models.CharField(blank=True, max_length=50, null=True)),
                ('birthday_of_children', models.DateField(blank=True, max_length=30, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
            ],
        ),
    ]
