# Generated by Django 4.0.5 on 2022-10-13 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_children'),
    ]

    operations = [
        migrations.CreateModel(
            name='Probationary_period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, max_length=30, null=True)),
                ('to_date', models.DateField(blank=True, max_length=30, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
            ],
        ),
    ]
