# Generated by Django 4.0.5 on 2022-10-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_probationary_period_letter_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='probationary_period',
            name='monthly_allowance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='probationary_period',
            name='monthly_gross_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
