# Generated by Django 4.0.5 on 2022-10-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_probationary_period_monthly_allowance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
