# Generated by Django 4.0.5 on 2022-10-20 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employee_bank_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department_area',
        ),
        migrations.DeleteModel(
            name='Department_area',
        ),
    ]
