# Generated by Django 4.0.5 on 2022-10-20 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_remove_employee_department_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='job_title',
        ),
        migrations.DeleteModel(
            name='Job_title',
        ),
    ]
