# Generated by Django 4.0.5 on 2022-10-20 10:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_remove_employee_job_title_delete_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abbreviation_Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abb_position', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='abb_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.abbreviation_position'),
        ),
    ]
