# Generated by Django 4.0.5 on 2022-10-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_employee_promotion_decision_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='with_bank',
            new_name='bank',
        ),
    ]
