# Generated by Django 4.0.5 on 2022-10-20 13:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_rename_hi_registered_place_hi_medical_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_info_submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_info_submission', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='da_nop_thong_tin_nhan_vien',
        ),
        migrations.DeleteModel(
            name='Da_nop_thong_tin_nhan_vien',
        ),
        migrations.AddField(
            model_name='employee',
            name='staff_info_submisstion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.staff_info_submission'),
        ),
    ]
