# Generated by Django 4.0.5 on 2022-10-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_staff_info_submission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='bo_sung_ho_so',
        ),
        migrations.AddField(
            model_name='employee',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Bo_sung_ho_so',
        ),
    ]
