# Generated by Django 4.0.5 on 2022-10-22 18:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_remove_employee_bo_sung_ho_so_employee_remark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='contract_no',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='signed_contract_date',
        ),
        migrations.CreateModel(
            name='Employee_contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_no', models.CharField(blank=True, max_length=50, null=True)),
                ('signed_contract_date', models.DateField(blank=True, max_length=30, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('contract_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.contract_type')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
            ],
        ),
    ]
