# Generated by Django 4.0.5 on 2022-10-22 18:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_remove_employee_contract_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='promotion_decision_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='promotion_effective_date',
        ),
        migrations.CreateModel(
            name='Employee_promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_effective_date', models.DateField(blank=True, max_length=30, null=True)),
                ('promotion_decision_number', models.CharField(blank=True, max_length=10, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
            ],
        ),
    ]
