# Generated by Django 4.0.5 on 2022-11-06 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_university_employee_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_children',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='employee_children',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_children',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_children',
            name='deleted_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_children',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_children',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_contract',
            name='basic_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_contract',
            name='lunch_support',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_contract',
            name='responsibility_allowance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_contract',
            name='telephone_support',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_contract',
            name='transportation_support',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
