# Generated by Django 4.0.5 on 2022-11-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_employee_contract_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='probationary_period',
            name='letter_returning_date',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
    ]
