# Generated by Django 4.0.5 on 2022-11-16 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_leave_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_application',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_by', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='temporary_replacement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='temporary_replacement', to='employee.employee'),
        ),
    ]
