# Generated by Django 4.0.5 on 2022-11-16 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_leave_application_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Minute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='leave_application',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='leave_application',
            name='to_time',
        ),
        migrations.AddField(
            model_name='leave_application',
            name='from_hour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_hour', to='employee.hour'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='from_minute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_minute', to='employee.minute'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='to_hour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_hour', to='employee.hour'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='to_minute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_minute', to='employee.minute'),
        ),
    ]
