# Generated by Django 4.0.5 on 2022-11-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0026_rename_leave_type_type_of_leave_leave_type_eng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_application',
            name='contact_person',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='relation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
