# Generated by Django 4.0.5 on 2022-11-17 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0028_status_leave_application_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave_application',
            old_name='from_date',
            new_name='annual_from_date',
        ),
        migrations.RenameField(
            model_name='leave_application',
            old_name='number_of_leave_days',
            new_name='annual_number_of_leave_days',
        ),
        migrations.RenameField(
            model_name='leave_application',
            old_name='remark',
            new_name='annual_remark',
        ),
        migrations.RenameField(
            model_name='leave_application',
            old_name='to_date',
            new_name='annual_to_date',
        ),
        migrations.RemoveField(
            model_name='leave_application',
            name='from_hour',
        ),
        migrations.RemoveField(
            model_name='leave_application',
            name='from_minute',
        ),
        migrations.RemoveField(
            model_name='leave_application',
            name='leave_type',
        ),
        migrations.RemoveField(
            model_name='leave_application',
            name='to_hour',
        ),
        migrations.RemoveField(
            model_name='leave_application',
            name='to_minute',
        ),
        migrations.AddField(
            model_name='leave_application',
            name='annual_from_hour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='annual_from_hour', to='employee.hour'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='annual_from_minute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='annual_from_minute', to='employee.minute'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='annual_to_hour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='annual_to_hour', to='employee.hour'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='annual_to_minute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='annual_to_minute', to='employee.minute'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='bereavement_from_date',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='bereavement_from_hour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bereavement_from_hour', to='employee.hour'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='bereavement_from_minute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bereavement_from_minute', to='employee.minute'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='bereavement_number_of_leave_days',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='bereavement_remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='bereavement_to_date',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='bereavement_to_hour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bereavement_to_hour', to='employee.hour'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='bereavement_to_minute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bereavement_to_minute', to='employee.minute'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='maternity_obstetric_from_date',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='maternity_obstetric_from_hour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maternity_obstetric_from_hour', to='employee.hour'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='maternity_obstetric_from_minute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maternity_obstetric_from_minute', to='employee.minute'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='maternity_obstetric_number_of_leave_days',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='maternity_obstetric_remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='maternity_obstetric_to_date',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='maternity_obstetric_to_hour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maternity_obstetric_to_hour', to='employee.hour'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='maternity_obstetric_to_minute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maternity_obstetric_to_minute', to='employee.minute'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='non_paid_from_date',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='non_paid_from_hour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='non_paid_from_hour', to='employee.hour'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='non_paid_from_minute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='non_paid_from_minute', to='employee.minute'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='non_paid_number_of_leave_days',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='non_paid_remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='non_paid_to_date',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='non_paid_to_hour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='non_paid_to_hour', to='employee.hour'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='non_paid_to_minute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='non_paid_to_minute', to='employee.minute'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='offinlieu_from_date',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='offinlieu_from_hour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offinlieu_from_hour', to='employee.hour'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='offinlieu_from_minute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offinlieu_from_minute', to='employee.minute'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='offinlieu_number_of_leave_days',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='offinlieu_remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='offinlieu_to_date',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='offinlieu_to_hour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offinlieu_to_hour', to='employee.hour'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='offinlieu_to_minute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offinlieu_to_minute', to='employee.minute'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='other_from_date',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='other_from_hour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='other_from_hour', to='employee.hour'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='other_from_minute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='other_from_minute', to='employee.minute'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='other_number_of_leave_days',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='other_remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='other_to_date',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='other_to_hour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='other_to_hour', to='employee.hour'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='other_to_minute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='other_to_minute', to='employee.minute'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='sick_from_date',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='sick_from_hour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sick_from_hour', to='employee.hour'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='sick_from_minute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sick_from_minute', to='employee.minute'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='sick_number_of_leave_days',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='sick_remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='sick_to_date',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='sick_to_hour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sick_to_hour', to='employee.hour'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='sick_to_minute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sick_to_minute', to='employee.minute'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='wedding_from_date',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='wedding_from_hour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wedding_from_hour', to='employee.hour'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='wedding_from_minute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wedding_from_minute', to='employee.minute'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='wedding_number_of_leave_days',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='wedding_remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='wedding_to_date',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='wedding_to_hour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wedding_to_hour', to='employee.hour'),
        ),
        migrations.AddField(
            model_name='leave_application',
            name='wedding_to_minute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wedding_to_minute', to='employee.minute'),
        ),
    ]
