# Generated by Django 4.0.5 on 2022-11-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0030_remove_leave_application_annual_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_application',
            name='total_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
