# Generated by Django 4.0.5 on 2022-11-17 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0032_rename_bereavment_from_leave_application_bereavement_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave_application',
            old_name='ofinlieu_from',
            new_name='offinlieu_from',
        ),
        migrations.RenameField(
            model_name='leave_application',
            old_name='ofinlieu_to',
            new_name='offinlieu_to',
        ),
    ]
