# Generated by Django 4.0.5 on 2022-11-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0033_rename_ofinlieu_from_leave_application_offinlieu_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_application',
            name='total_days',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
