# Generated by Django 4.0.5 on 2022-11-18 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0035_alter_leave_application_emergency_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='employee.employee')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manager_of_employee', to='employee.employee')),
            ],
        ),
    ]
