# Generated by Django 4.0.5 on 2022-11-18 14:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0036_employee_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_application',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leave_approved_by', to='employee.employee'),
        ),
        migrations.CreateModel(
            name='Overtime_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, default=11, max_length=5, null=True)),
                ('ot_date', models.DateField(blank=True, max_length=30, null=True)),
                ('ot_time_from', models.TimeField(blank=True, max_length=30, null=True)),
                ('ot_time_to', models.TimeField(blank=True, max_length=30, null=True)),
                ('ot_total_time', models.FloatField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_date', models.DateField(blank=True, max_length=30, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ot_approved_by', to='employee.employee')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.status')),
            ],
        ),
    ]
