# Generated by Django 4.0.5 on 2022-11-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0037_alter_leave_application_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime_application',
            name='application_date',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
    ]
