# Generated by Django 4.0.5 on 2022-11-23 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0038_overtime_application_application_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime_application',
            name='hr_approved_date',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='overtime_application',
            name='hr_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hr_status', to='employee.status'),
        ),
    ]
