# Generated by Django 4.0.5 on 2022-12-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0040_leave_application_hr_approved_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_application',
            name='temporary_replacement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='overtime_application',
            name='month',
            field=models.CharField(blank=True, default=12, max_length=5, null=True),
        ),
    ]
