# Generated by Django 4.0.5 on 2022-12-07 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0042_employee_dayoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_manager',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee', to='employee.employee'),
        ),
    ]
