# Generated by Django 4.0.5 on 2022-12-12 10:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0045_alter_employee_dayoff_total_dayoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change_dayoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plus_dayoff', models.IntegerField(blank=True, default=12, null=True)),
                ('minus_dayoff', models.IntegerField(blank=True, null=True)),
                ('reason_of_changing', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dayoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_dayoff', models.IntegerField(blank=True, default=12, null=True)),
                ('remain_dayoff', models.IntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.CharField(blank=True, max_length=5, null=True)),
                ('start_period_date', models.DateField(blank=True, max_length=30, null=True)),
                ('end_period_date', models.DateField(blank=True, max_length=30, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee_dayoff',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Hour',
        ),
        migrations.DeleteModel(
            name='Minute',
        ),
        migrations.DeleteModel(
            name='Employee_dayoff',
        ),
        migrations.AddField(
            model_name='dayoff',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.period'),
        ),
        migrations.AddField(
            model_name='change_dayoff',
            name='day_off',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.dayoff'),
        ),
    ]
