# Generated by Django 4.0.5 on 2022-12-12 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0046_change_dayoff_dayoff_period_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Change_dayoff',
            new_name='Update_dayoff',
        ),
    ]
