# Generated by Django 4.0.5 on 2022-12-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0047_rename_change_dayoff_update_dayoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='total_months',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
