# Generated by Django 4.0.5 on 2022-12-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0049_alter_employee_years_of_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='joining_year',
            field=models.IntegerField(null=True),
        ),
    ]
