# Generated by Django 4.0.5 on 2022-12-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0051_alter_employee_joining_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='period_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
