# Generated by Django 4.0.5 on 2022-12-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0053_alter_employee_years_of_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='years_of_service',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
