# Generated by Django 4.0.5 on 2022-12-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0054_alter_employee_years_of_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update_dayoff',
            name='plus_dayoff',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
