# Generated by Django 4.0.5 on 2022-12-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0057_update_recuperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayoff',
            name='previous_remain_dayoff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dayoff',
            name='previous_remain_recuperation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
