# Generated by Django 4.0.5 on 2022-12-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0059_month_in_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='month_in_period',
            name='month_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
