# Generated by Django 4.0.5 on 2022-12-26 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0060_month_in_period_month_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='month_in_period',
            old_name='month',
            new_name='month_number',
        ),
    ]
