# Generated by Django 4.0.5 on 2022-12-27 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0062_day_in_month_in_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day_in_month_in_period',
            name='holidays',
        ),
        migrations.RemoveField(
            model_name='day_in_month_in_period',
            name='month_name',
        ),
        migrations.RemoveField(
            model_name='day_in_month_in_period',
            name='month_number',
        ),
        migrations.RemoveField(
            model_name='day_in_month_in_period',
            name='period',
        ),
        migrations.RemoveField(
            model_name='day_in_month_in_period',
            name='total_days',
        ),
        migrations.RemoveField(
            model_name='day_in_month_in_period',
            name='total_work_days',
        ),
        migrations.AddField(
            model_name='day_in_month_in_period',
            name='date',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='day_in_month_in_period',
            name='leave',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.leave_application'),
        ),
        migrations.AddField(
            model_name='day_in_month_in_period',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.month_in_period'),
        ),
        migrations.AddField(
            model_name='day_in_month_in_period',
            name='weekno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
