# Generated by Django 4.0.5 on 2022-12-27 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0063_remove_day_in_month_in_period_holidays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='day_in_month_in_period',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.employee'),
        ),
    ]
