# Generated by Django 4.0.5 on 2022-12-28 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0064_day_in_month_in_period_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day_in_month_in_period',
            name='leave',
        ),
        migrations.AddField(
            model_name='day_in_month_in_period',
            name='dayoff_change',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.update_dayoff'),
        ),
        migrations.AddField(
            model_name='update_dayoff',
            name='leave_application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.leave_application'),
        ),
    ]
