# Generated by Django 4.0.5 on 2023-01-05 10:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0065_remove_day_in_month_in_period_leave_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, max_length=100, null=True)),
                ('weekend', models.BooleanField(blank=True, null=True)),
                ('holiday', models.BooleanField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.month_in_period')),
            ],
        ),
        migrations.CreateModel(
            name='Daily_work_for_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave', models.BooleanField(blank=True, null=True)),
                ('overtime', models.BooleanField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('daily_work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.daily_work')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
                ('leave_application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.leave_application')),
            ],
        ),
        migrations.AlterField(
            model_name='overtime_application',
            name='month',
            field=models.CharField(blank=True, default=1, max_length=5, null=True),
        ),
        migrations.DeleteModel(
            name='Day_in_month_in_period',
        ),
        migrations.AddField(
            model_name='daily_work_for_employee',
            name='overtime_application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.overtime_application'),
        ),
    ]
