# Generated by Django 4.0.5 on 2023-01-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0067_rename_leave_daily_work_for_employee_paid_leave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime_application',
            name='ot_paid_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overtime_application',
            name='ot_unpaid_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
