# Generated by Django 4.0.5 on 2023-01-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0068_overtime_application_ot_paid_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime_application',
            name='ot_unpaid_day',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
