# Generated by Django 4.0.5 on 2023-01-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0070_alter_daily_work_for_employee_overtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_work_for_employee',
            name='overtime',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daily_work_for_employee',
            name='paid_leave',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daily_work_for_employee',
            name='unpaid_leave',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
