# Generated by Django 4.0.5 on 2023-02-02 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0076_alter_daily_work_for_employee_paid_leave_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayoff',
            name='previous_remain_recuperation',
        ),
        migrations.RemoveField(
            model_name='dayoff',
            name='remain_recuperation',
        ),
        migrations.RemoveField(
            model_name='dayoff',
            name='total_recuperation',
        ),
        migrations.RemoveField(
            model_name='dayoff',
            name='used_recuperation',
        ),
    ]
