# Generated by Django 4.0.5 on 2023-02-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0077_remove_dayoff_previous_remain_recuperation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update_dayoff',
            old_name='leave_application',
            new_name='application',
        ),
        migrations.DeleteModel(
            name='Update_recuperation',
        ),
    ]
