# Generated by Django 4.0.5 on 2023-02-02 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0078_rename_leave_application_update_dayoff_application_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update_dayoff',
            old_name='application',
            new_name='leave_application',
        ),
        migrations.AddField(
            model_name='update_dayoff',
            name='ot_application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.overtime_application'),
        ),
    ]
