# Generated by Django 4.0.5 on 2023-02-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0079_rename_application_update_dayoff_leave_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_work_for_employee',
            name='ot_time',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
