# Generated by Django 4.0.5 on 2023-03-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0081_alter_overtime_application_month_payroll_vietha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_contract',
            name='seniority_bonus',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
