# Generated by Django 4.0.5 on 2023-03-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0082_employee_contract_seniority_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_contract',
            name='travel_support',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
