# Generated by Django 4.0.5 on 2023-04-14 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0085_report_payroll_tedis'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report_Payroll_Tedis',
            new_name='Report_PIT_Payroll_Tedis',
        ),
    ]
