# Generated by Django 4.0.5 on 2023-04-21 16:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0088_report_pit_payroll_tedis_vietha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_Payment_Payroll_Tedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=10, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('paidby', models.CharField(blank=True, max_length=10, null=True)),
                ('paidto', models.CharField(blank=True, max_length=10, null=True)),
                ('account_no', models.TextField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.month_in_period')),
            ],
        ),
    ]
