# Generated by Django 4.0.5 on 2023-05-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0089_report_payment_payroll_tedis'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_pit_payroll_tedis_vietha',
            name='individual_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='overtime_application',
            name='month',
            field=models.CharField(blank=True, default=5, max_length=5, null=True),
        ),
    ]
