# Generated by Django 4.0.5 on 2023-05-16 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0092_report_transfer_payroll_tedis_vietha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_transfer_payroll_tedis_vietha',
            name='payroll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.payroll_tedis_vietha'),
        ),
    ]
