# Generated by Django 4.0.5 on 2023-05-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0093_alter_report_transfer_payroll_tedis_vietha_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_transfer_payroll_tedis_vietha',
            name='employee_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
