# Generated by Django 4.0.5 on 2023-05-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0094_report_transfer_payroll_tedis_vietha_employee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_work_for_employee',
            name='work',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
