# Generated by Django 4.0.5 on 2023-06-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0095_daily_work_for_employee_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime_application',
            name='month',
            field=models.CharField(blank=True, default=6, max_length=5, null=True),
        ),
    ]
