# Generated by Django 4.0.5 on 2023-06-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0098_payroll_ser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_payment_payroll_tedis_vietha',
            name='area',
        ),
    ]
