# Generated by Django 4.0.5 on 2023-06-20 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0099_remove_report_payment_payroll_tedis_vietha_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll_ser',
            old_name='total_cost_euro',
            new_name='total_cost_usd',
        ),
    ]
