# Generated by Django 4.0.5 on 2023-06-27 16:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0100_rename_total_cost_euro_payroll_ser_total_cost_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_contract',
            name='basic_salary',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee_contract',
            name='lunch_support',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee_contract',
            name='responsibility_allowance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee_contract',
            name='seniority_bonus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee_contract',
            name='telephone_support',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee_contract',
            name='transportation_support',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee_contract',
            name='travel_support',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='probationary_period',
            name='monthly_allowance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='probationary_period',
            name='monthly_gross_salary',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Report_resigned_staff_Tedis_VietHa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateField(max_length=50, null=True)),
                ('leaving_date', models.DateField(max_length=50, null=True)),
                ('allowance', models.FloatField(blank=True, null=True)),
                ('unused_AL', models.CharField(blank=True, max_length=200, null=True)),
                ('month_13_salary', models.FloatField(blank=True, default=0, null=True)),
                ('severance_allowance', models.FloatField(blank=True, null=True)),
                ('other_allowance', models.FloatField(blank=True, null=True)),
                ('incentive', models.FloatField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.department_e')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.month_in_period')),
            ],
        ),
        migrations.CreateModel(
            name='Report_other_changes_Tedis_VietHa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_salary', models.FloatField(blank=True, default=0, null=True)),
                ('allowance', models.FloatField(blank=True, null=True)),
                ('effective_date', models.DateField(max_length=50, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.month_in_period')),
            ],
        ),
        migrations.CreateModel(
            name='Report_new_staff_Tedis_VietHa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateField(max_length=50, null=True)),
                ('gross_salary', models.FloatField(blank=True, null=True)),
                ('allowance', models.FloatField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('dependant_deduction', models.FloatField(blank=True, null=True)),
                ('hospital_for_HI', models.CharField(blank=True, max_length=100, null=True)),
                ('account_no', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=30, null=True)),
                ('PIT_code', models.IntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.department_e')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.month_in_period')),
            ],
        ),
        migrations.CreateModel(
            name='Report_maternity_leave_Tedis_VietHa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(max_length=50, null=True)),
                ('to_date', models.DateField(max_length=50, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.department_e')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.month_in_period')),
            ],
        ),
        migrations.CreateModel(
            name='Report_confirmed_after_probation_Tedis_VietHa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateField(max_length=50, null=True)),
                ('sign_LC_date', models.DateField(max_length=50, null=True)),
                ('allowance', models.FloatField(blank=True, null=True)),
                ('salary_after_probation', models.FloatField(blank=True, null=True)),
                ('SI_book_no', models.IntegerField(blank=True, null=True)),
                ('hospital_for_HI', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.department_e')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.month_in_period')),
            ],
        ),
    ]
