# Generated by Django 4.0.5 on 2023-07-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0102_employee_active_employee_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_application',
            name='annual_from',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='annual_to',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='overtime_application',
            name='month',
            field=models.CharField(blank=True, default=7, max_length=5, null=True),
        ),
    ]
