# Generated by Django 4.0.5 on 2023-07-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0105_alter_leave_application_annual_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_confirmed_after_probation_tedis_vietha',
            name='SI_book_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
