# Generated by Django 4.0.5 on 2023-07-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0106_alter_report_confirmed_after_probation_tedis_vietha_si_book_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_resigned_staff_tedis_vietha',
            name='unused_AL',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
    ]
