# Generated by Django 4.0.5 on 2023-07-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0107_alter_report_resigned_staff_tedis_vietha_unused_al'),
    ]

    operations = [
        migrations.RenameField(
            model_name='month_in_period',
            old_name='total_work_days',
            new_name='total_work_days_bo',
        ),
        migrations.AddField(
            model_name='month_in_period',
            name='total_work_days_wh',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
