# Generated by Django 4.0.5 on 2023-08-09 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0109_report_reconcile_tedis_vietha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='abb_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.abbreviation_position'),
        ),
        migrations.AlterField(
            model_name='overtime_application',
            name='month',
            field=models.CharField(blank=True, default=8, max_length=5, null=True),
        ),
    ]
