# Generated by Django 4.0.5 on 2023-08-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0110_alter_employee_abb_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bank_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='company_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_card_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='major_e',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='major_v',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
