# Generated by Django 4.0.5 on 2023-08-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0111_alter_employee_bank_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll_tedis',
            name='nontaxable_overtime',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='payroll_tedis',
            name='taxable_overtime',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
