# Generated by Django 4.0.5 on 2023-09-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0112_payroll_tedis_nontaxable_overtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='years_of_service',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='overtime_application',
            name='month',
            field=models.CharField(blank=True, default=9, max_length=5, null=True),
        ),
    ]
