# Generated by Django 4.0.5 on 2023-10-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0114_alter_overtime_application_month_payroll_marjorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sub_department_1',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='sub_department_2',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='sub_department_3',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
