# Generated by Django 4.0.5 on 2023-10-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0115_employee_sub_department_1_employee_sub_department_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sub_province',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
