# Generated by Django 4.0.5 on 2023-11-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0120_report_landing_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll_tedis_vietha',
            name='overtime',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
