# Generated by Django 4.0.5 on 2023-11-15 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0121_payroll_tedis_vietha_overtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_landing_achievement',
            name='period',
        ),
        migrations.RemoveField(
            model_name='report_landing_target_value',
            name='period',
        ),
        migrations.AddField(
            model_name='report_landing_achievement',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.month_in_period'),
        ),
        migrations.AddField(
            model_name='report_landing_target_value',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.month_in_period'),
        ),
    ]
