# Generated by Django 4.0.5 on 2024-01-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0123_alter_overtime_application_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month_in_period',
            name='total_work_days_bo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='month_in_period',
            name='total_work_days_wh',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
