# Generated by Django 4.0.5 on 2024-01-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0125_payroll_vietha_travel'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll_vietha',
            name='seniority_bonus',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
