# Generated by Django 4.0.5 on 2024-01-26 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0127_report_company_celebration_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report_company_celebration_rate',
            old_name='year',
            new_name='period',
        ),
    ]
