# Generated by Django 4.0.5 on 2022-11-16 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_leave_application'),
        ('hr', '0003_permission_user_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.employee'),
        ),
    ]
