# Generated by Django 4.0.5 on 2023-04-11 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0084_rename_occupational_accident_and_disease_ins_0point5percent_pay_for_staffs_payroll_tedis_occupationa'),
        ('hr', '0004_user_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.employee'),
        ),
    ]
